### ISSUE TITLE
How to cite the project?

### ISSUE THREAD

**Issue by napoles-uach** [wells-wood-research/timed-design#29]
Hi @universvm, nice work!
I just want to ask if you have a preferred way to cite the project!
Thanks

**Comment by universvm** [comment]
Hi @napoles-uach , we are still finishing up the tool and hopefully publish it on Arxiv. I can email you once we have a link?

**Comment by napoles-uach** [comment]
It's ok, thanks!

**Comment by universvm** [comment]
Hi @napoles-uach ,

As promised you can cite us using this DOI: https://zenodo.org/record/6997495

This is a temporary submission. 

Attached you will find the screenshots you requested :)
[Archive.zip](https://github.com/universvm/timed-gif/files/9349589/Archive.zip)
